### ISSUE TITLE
lurk panics with VirtualBox 7.1

### ISSUE THREAD

**Issue by thorstenhirsch** [JakWai01/lurk#51]
I tried to use lurk for investigating a problem with VirtualBox (a segfault is thrown when starting a VM), but it throws a panic before I can trigger the problem:
```sh
$ lurk virtualbox      
[129757] execve("", "", "") = 0
[129757] brk(0x0) = 0x55555566F000
[129757] access("/etc/ld.so.preload", 4) = -2
[129757] openat(4294967196, "/etc/ld.so.cache", 524288) = 3
[129757] fstat(3, 0x7FFFFFFFCC40) = 0
[129757] mmap(0x0, 186063, 1, 2, 3, 0) = 0x7FFFF7F93000
[129757] close(3) = 0
[129757] openat(4294967196, "/usr/lib/libreadline.so.8", 524288) = 3
[129757] read(3, "ELF\u0002\u0001\u0001", 832) = 832
[129757] fstat(3, 0x7FFFFFFFCC40) = 0
[129757] mmap(0x0, 8192, 3, 34, 4294967295, 0) = 0x7FFFF7F91000
[129757] mmap(0x0, 350904, 1, 2050, 3, 0) = 0x7FFFF7F3B000
[129757] mmap(0x7FFFF7F50000, 188416, 5, 2066, 3, 86016) = 0x7FFFF7F50000
[129757] mmap(0x7FFFF7F7E000, 36864, 1, 2066, 3, 274432) = 0x7FFFF7F7E000
[129757] mmap(0x7FFFF7F87000, 36864, 3, 2066, 3, 307200) = 0x7FFFF7F87000
[129757] mmap(0x7FFFF7F90000, 2744, 3, 50, 4294967295, 0) = 0x7FFFF7F90000
[129757] close(3) = 0
[129757] openat(4294967196, "/usr/lib/libc.so.6", 524288) = 3
[129757] read(3, "ELF\u0002\u0001\u0001\u0003", 832) = 832
[129757] pread64(3, "\u0006", 784, 64) = 784
[129757] fstat(3, 0x7FFFFFFFCC20) = 0
[129757] pread64(3, "\u0006", 784, 64) = 784
[129757] mmap(0x0, 2034616, 1, 2050, 3, 0) = 0x7FFFF7D4A000
[129757] mmap(0x7FFFF7D6E000, 1511424, 5, 2066, 3, 147456) = 0x7FFFF7D6E000
[129757] mmap(0x7FFFF7EDF000, 319488, 1, 2066, 3, 1658880) = 0x7FFFF7EDF000
[129757] mmap(0x7FFFF7F2D000, 24576, 3, 2066, 3, 1978368) = 0x7FFFF7F2D000
[129757] mmap(0x7FFFF7F33000, 31672, 3, 50, 4294967295, 0) = 0x7FFFF7F33000
[129757] close(3) = 0
[129757] openat(4294967196, "/usr/lib/libncursesw.so.6", 524288) = 3
[129757] read(3, "ELF\u0002\u0001\u0001", 832) = 832
[129757] fstat(3, 0x7FFFFFFFCC00) = 0
[129757] mmap(0x0, 453856, 1, 2050, 3, 0) = 0x7FFFF7CDB000
[129757] mmap(0x7FFFF7CE8000, 290816, 5, 2066, 3, 53248) = 0x7FFFF7CE8000
[129757] mmap(0x7FFFF7D2F000, 90112, 1, 2066, 3, 344064) = 0x7FFFF7D2F000
[129757] mmap(0x7FFFF7D45000, 20480, 3, 2066, 3, 434176) = 0x7FFFF7D45000
[129757] close(3) = 0
[129757] mmap(0x0, 8192, 3, 34, 4294967295, 0) = 0x7FFFF7CD9000
[129757] arch_prctl(4098, 0x7FFFF7CD9B80) = 0
[129757] set_tid_address(0x7FFFF7CD9E50) = 0x1FADD
[129757] set_robust_list(0x7FFFF7CD9E60, 24) = 0
[129757] rseq() = 0
[129757] mprotect(0x7FFFF7F2D000, 16384, 1) = 0
[129757] mprotect(0x7FFFF7D45000, 16384, 1) = 0
[129757] mprotect(0x7FFFF7F87000, 12288, 1) = 0
[129757] mprotect(0x55555565F000, 12288, 1) = 0
[129757] mprotect(0x7FFFF7FFB000, 8192, 1) = 0
[129757] prlimit64(0, 3, 0x0, 0x7FFFFFFFD7A0) = 0
[129757] munmap(0x7FFFF7F93000, 186063) = 0
[129757] openat(4294967196, "/dev/tty", 2050) = 3
[129757] close(3) = 0
[129757] getrandom("ç\u0011gK\u000fák", 8, 1) = 8
[129757] brk(0x0) = 0x55555566F000
[129757] brk(0x555555690000) = 0x555555690000
[129757] openat(4294967196, "/usr/lib/locale/locale-archive", 524288) = 3
[129757] fstat(3, 0x7FFFF7F32800) = 0
[129757] mmap(0x0, 3420784, 1, 2, 3, 0) = 0x7FFFF7800000
[129757] close(3) = 0
[129757] openat(4294967196, "/usr/lib/gconv/gconv-modules.cac...", 524288) = 3
[129757] fstat(3, 0x7FFFFFFFD530) = 0
[129757] mmap(0x0, 27010, 1, 1, 3, 0) = 0x7FFFF7FBA000
[129757] close(3) = 0
[129757] futex(0x7FFFF7F3272C, 129, 2147483647, 0x0, 3, 0) = 0
[129757] getuid(0x7FFFF7F32920) = 501
[129757] getgid(0x0) = 100
[129757] geteuid(0x0) = 501
[129757] getegid(0x0) = 100
[129757] rt_sigprocmask(0, 0x0, 0x5555556660A8, 8) = 0
[129757] rt_sigaction(17, 0x7FFFFFFFD4A0, 0x7FFFFFFFD540) = 0
[129757] rt_sigaction(17, 0x7FFFFFFFD4A0, 0x7FFFFFFFD540) = 0
[129757] rt_sigaction(2, 0x7FFFFFFFD4A0, 0x7FFFFFFFD540) = 0
[129757] rt_sigaction(2, 0x7FFFFFFFD4A0, 0x7FFFFFFFD540) = 0
[129757] rt_sigaction(3, 0x7FFFFFFFD4A0, 0x7FFFFFFFD540) = 0
[129757] rt_sigaction(3, 0x7FFFFFFFD4A0, 0x7FFFFFFFD540) = 0
[129757] rt_sigaction(20, 0x7FFFFFFFD480, 0x7FFFFFFFD520) = 0
[129757] rt_sigaction(20, 0x7FFFFFFFD480, 0x7FFFFFFFD520) = 0
[129757] rt_sigaction(21, 0x7FFFFFFFD480, 0x7FFFFFFFD520) = 0
[129757] rt_sigaction(21, 0x7FFFFFFFD480, 0x7FFFFFFFD520) = 0
[129757] rt_sigaction(22, 0x7FFFFFFFD480, 0x7FFFFFFFD520) = 0
[129757] rt_sigaction(22, 0x7FFFFFFFD480, 0x7FFFFFFFD520) = 0
[129757] rt_sigprocmask(0, 0x0, 0x555555665CA0, 8) = 0
[129757] rt_sigaction(3, 0x7FFFFFFFD4A0, 0x7FFFFFFFD540) = 0
[129757] uname(0x7FFFFFFFD5C0) = 0
[129757] newfstatat(4294967196, "/home/torti", 0x7FFFFFFFD4D0, 0) = 0
[129757] newfstatat(4294967196, ".", 0x7FFFFFFFD440, 0) = 0
[129757] newfstatat(4294967196, "/home", 0x7FFFFFFFD4C0, 0) = 0
[129757] newfstatat(4294967196, "/home/torti", 0x7FFFFFFFD4C0, 0) = 0
[129757] newfstatat(4294967196, "/home/torti", 0x7FFFFFFFD5A0, 0) = 0
[129757] getpid(0x55555567A990) = 0x1FADD
[129757] getppid(0x1) = 0x1FADC
[129757] getpid(0x7FFFFFFFD630) = 0x1FADD
[129757] getppid(0x7FFFFFFFD630) = 0x1FADC
[129757] getpid(0x7FFFFFFFD640) = 0x1FADD
[129757] getppid(0x7FFFFFFFD640) = 0x1FADC
[129757] getpgrp(0x0) = 0x1FADC
[129757] ioctl(2, 21519, 0x7FFFFFFFD714) = 0
[129757] rt_sigaction(17, 0x7FFFFFFFD470, 0x7FFFFFFFD510) = 0
[129757] prlimit64(0, 6, 0x0, 0x7FFFFFFFD6E0) = 0
[129757] rt_sigprocmask(0, 0x0, 0x555555666188, 8) = 0
[129757] openat(4294967196, "/usr/bin/virtualbox", 0) = 3
[129757] newfstatat(4294967196, "/usr/bin/virtualbox", 0x7FFFFFFFD810, 0) = 0
[129757] ioctl(3, 21505, 0x7FFFFFFFD820) = -25
[129757] lseek(3, 0, 1) = 0
[129757] read(3, "#!/bin/sh\n## @file\n# Oracle Virt...", 80) = 80
[129757] lseek(3, 0, 0) = 0
[129757] prlimit64(0, 7, 0x0, 0x7FFFFFFFD850) = 0
[129757] fcntl(255, 1) = -9
[129757] dup2(3, 255) = 255
[129757] close(3) = 0
[129757] fcntl(255, 2) = 0
[129757] fcntl(255, 3) = 32768
[129757] fstat(255, 0x7FFFFFFFD7D0) = 0
[129757] lseek(255, 0, 1) = 0
[129757] read(255, "#!/bin/sh\n## @file\n# Oracle Virt...", 5875) = 5875
[129757] pipe2(140737488342904, 0) = 0
[129757] rt_sigprocmask(0, 0x7FFFFFFFCE70, 0x7FFFFFFFCDF0, 8) = 0
[129757] rt_sigprocmask(2, 0x7FFFFFFFCDF0, 0x0, 8) = 0
[129757] rt_sigprocmask(0, 0x0, 0x7FFFFFFFCC30, 8) = 0
[129757] rt_sigprocmask(0, 0x7FFFFFFFCD30, 0x7FFFFFFFCCB0, 8) = 0
[129757] lseek(255, -4817, 1) = 1058
[129757] clone(0x1200011, 0) = 0x1FADE
[129757] rt_sigprocmask(2, 0x7FFFFFFFCCB0, 0x0, 8) = 0
[129757] rt_sigaction(17, 0x7FFFFFFFCDE0, 0x7FFFFFFFCE80) = 0
[129757] close(4) = 0
[129757] rt_sigprocmask(0, 0x7FFFFFFFD020, 0x7FFFFFFFCF80, 8) = 0
[129757] read(3, "/usr/bin/VBox\n", 4096) = 14
[129757] read(3, "/usr/bin/VBox\n", 4096) = 0
[129757] close(3) = 0
[129757] wait4(4294967295, 140737488339664, 1, 0x0) = 0x1FADE
[129757] wait4(4294967295, 140737488339664, 1, 0x0) = -10
thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syscalls-0.6.18/src/arch/x86_64.rs:5:1:
invalid syscall: 4294967295
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
So, this happens when opening the Qt6 GUI of VirtualBox. The application is running fine at this state, so I don't know why lurk crashes. The segmentation fault in VirtualBox I mentioned earlier only happens at a later point, so it is not the cause of lurk's crash.

system: arch linux, amd64, kernel 6.10.10
lurk version 0.3.7 installed via yay (aur, arch user repos)

**Comment by gepbird** [comment]
I get the same panic message when tracing nvim and saving a file:

```console
~ ❯ sudo -E lurk -p $(pidof nvim) | grep -v epoll_pwait 
[227021] mmap(0x7EC2B0C21000, 131072, 3, 34, 4294967295, 0) = 0x7EC2B0BE1000
[227021] read(11, "\u0002±nvim_ui_set_focusÃ¬term...", 4096) = 22
[227021] statx(4294967196, "/tmp/test", 0, 4095, "ÿ\u0002ªnvim_input¡ ocusÃ¬te...", 4096) = 16
[227021] write(12, "\u0002¦redrawÜ", 57) = 57
[227021] read(11, "\u0002ªnvim_input¡wocusÃ¬te...", 4096) = 16
[227021] mmap(0x7EC2B0BE1000, 131072, 3, 34, 4294967295, 0) = 0x7EC2B0BA1000
[227021] statx(4294967196, "/tmp/test", 0, 4095, "ÿ\u0002¦redrawÜ", 115) = 115
[227021] statx(4294967196, "/tmp/test", 0, 4095, "ÿ²Â~", 4095) = -22
[227021] statx(4294967196, "/home/gep/.local/state/nvim/undo...", 0, 4095, "ÿ\u0002¦redrawÜ", 109) = 109
[227021] read(21, "warning: Not a git repository. U...", 4096) = 1475
[227021] mprotect(0x7EC2A2F60000, 65536, 3) = 0
[227021] mprotect(0x7EC2A2F60000, 65536, 5) = 0
[227021] read(21, "generate diffstat with a given w...", 4096) = 4096
[227021] read(6, "*", 1) = 1
[227021] write(9, "(¾, 16) = 16
[227021] write(7, "*(¾, 1) = 1
thread 'main' panicked at /build/lurk-0.3.9-vendor.tar.gz/syscalls/src/arch/x86_64.rs:5:1:
invalid syscall: 4294967295
stack backtrace:
   0:     0x576036ba6f76 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h9754a6437f1de22a
   1:     0x576036bfa08b - core::fmt::write::hb706a393bb60a06f
   2:     0x576036baed19 - std::io::Write::write_fmt::h9b447dc5d824d0bd
   3:     0x576036bd8cc6 - std::panicking::default_hook::{{closure}}::h227952daede9dd84
   4:     0x576036bd8956 - std::panicking::default_hook::h31626ee1feb8ee2a
   5:     0x576036bd9221 - std::panicking::rust_panic_with_hook::h76d2aa694a00748e
   6:     0x576036ba77f7 - std::panicking::begin_panic_handler::{{closure}}::h8855a344ffa1638b
   7:     0x576036ba7189 - std::sys::backtrace::__rust_end_short_backtrace::h3110d0cbfbf26886
   8:     0x576036bd8e04 - rust_begin_unwind
   9:     0x576036a8bfc3 - core::panicking::panic_fmt::h3af706d0346c1c60
  10:     0x576036b50555 - <syscalls::arch::x86_64::Sysno as core::convert::From<u32>>::from::h11cbe6b055594b9d
  11:     0x576036a8f0a0 - lurk_cli::Tracer<W>::log_standard_syscall::h1e413ed6aa727906
  12:     0x576036a8d342 - lurk_cli::Tracer<W>::run_tracer::hef4e2d15ef1cdb38
  13:     0x576036a97e72 - lurk::main::h254ad2fa91dff1d6
  14:     0x576036aa1be3 - std::sys::backtrace::__rust_begin_short_backtrace::h12443bb163a31647
  15:     0x576036a9e87d - std::rt::lang_start::{{closure}}::he10191e4e51afed7
  16:     0x576036bdafb5 - std::rt::lang_start_internal::h2084fce485147f46
  17:     0x576036a97f75 - main
  18:     0x7c92ee4bb27e - __libc_start_call_main
  19:     0x7c92ee4bb339 - __libc_start_main_alias_2
  20:     0x576036a8c425 - _start
  21:                0x0 - <unknown>
```

**Comment by JakWai01** [comment]
Hi @gepbird & @tyilo! Just applied the patch in https://github.com/JakWai01/lurk/commit/168bd7b028b7b5a52ba9f3940781b2fa9fd05090!
